name: Deploy Storybook to CDN

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Dependencies
        run: yarn install  --frozen-lockfile
      - name: Build Storybook
        run: yarn build-storybook
  deploy:
    name: Deploy
    runs-on: ubuntu-16.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - name: Install firebase dependencies
        run: yarn global add firebase-tools
      - name: Deploy to Firebase Hosting
        run: yarn deploy-storybook --token ${{ secrets.FIREBASE_API_TOKEN }}
